language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
before_install:
    - pip install pytest-cov coveralls
install: "pip install ."
# command to run tests
script: py.test
after_success:
    - coveralls