language: python
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: false
    python: '2.6'
  - os: linux
    dist: trusty
    sudo: false
    python: '2.7'
  - os: linux
    dist: trusty
    sudo: false
    python: '3.3'
  - os: linux
    dist: trusty
    sudo: false
    python: '3.4'
  - os: linux
    dist: trusty
    sudo: false
    python: '3.5'
  - os: linux
    dist: trusty
    sudo: false
    python: '3.6'
  - os: linux
    dist: xenial
    sudo: false
    python: '3.7'
# command to install dependencies
before_install:
  - pip install coverage
  - pip install coveralls
install: 
  - pip install .
# command to run tests
script: 
  - coverage run --source longbow -m py.test
  - coverage report -m
after_success:
  - coveralls
