language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.7
# command to install dependencies
before_install:
  # Coverage 4.0+ doesn't support Python 3.2
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.2" ]; then travis_retry pip install coverage==3.7.1; fi
  - if [ "$TRAVIS_PYTHON_VERSION" != "3.2" ]; then travis_retry pip install coverage; fi
  - pip install coveralls
install: 
  - pip install .
# command to run tests
script: 
  - coverage run --source longbow -m py.test
  - coverage report -m
after_success:
  - coveralls
